;;;;;;;;;;;;;;; This is an .ini file containing the default values
 
[default]    
 ;;INST|d|Zabbix Server Address
 ServerActive=zabbix.plachy.euX

 ;;INST|am|Hostname Prefix (computer name will be appended)
 Hostname=Customer-X

 ;;INST|c|Log Type (auto-configured)
 LogType=file

 ;;INST|c|Log File Path (auto-configured)
 LogFile=%%INSTALL_PATH%%\log\agent\agent.log.txt

 ;;INST|m|Aggplugin executable path (auto-configured, Agent 2 only)
 Plugins.Aggplugin.System.Path=%%INSTALL_PATH%%\bin\aggplugin-agent2.exe

[bootstrap-silent-install-only]
 ;;Bootstrap parameters (set by web installer)
 InstallPath=C:\zabbix
 AutoAppendHostname=0
 AutoStart=1
 CreateLogs=1
 
[conf/privoxy/config.txt]
 usermanual=localhost

[conf/privoxy/user.action]
 usermanual=localhost


[%%INSTALL_PATH%%\conf\zabbix_agent2.d\plugins.d\aggplugin.conf]
;;INST|m|Plugin DLL path (auto-configured)
Plugins.Aggplugin.PluginPath=%%INSTALL_PATH%%\bin\plugins\*.dll
Plugins.Aggplugin.DebugLevel=4
Plugins.Aggplugin.MaxSamples=1000
Plugins.Aggplugin.PreloadMetrics=cpu_load,mem_free,disk.io.read,disk.io.write
Plugins.Aggplugin.PreloadDelay=2
