### Configuration for Aggplugin

Plugins.Aggplugin.DebugLevel=4
Plugins.Aggplugin.MaxSamples=1000
Plugins.Aggplugin.PreloadMetrics=cpu_load,mem_free,disk.io.read,disk.io.write
Plugins.Aggplugin.PreloadDelay=2
# PluginPath: Relative path to measurement plugin DLLs (relative to installation root)
Plugins.Aggplugin.PluginPath=\bin\plugins\*.dll
